### PR TITLE
Adds risk classification to transition risk scores using the user-facing `profile_transition_risk` function

### LINKED ISSUE #15: Implement Product Ranking and Classification Based on Transition Risk Scores
Dear @kalashsinghal, 

We need to implement a feature to rank and classify products based on their transition risk scores. This feature aims to provide insights into the relative risk levels of different products in our portfolio, enabling better risk management and decision-making. Please also provide me as soon as possible with the number of the low_threshold and the high_threshold for the benchmark "tilt_sector_unit_IPR_2030"

Here are the tasks that I think are included. Please also think about it independently and if you have a better solution in mind please adapt the task break-down:

1. Calculate the transition risk score for each product in our database that have an emission profile and a sector profile. Please use distinct activity_uuid_product_uuid. Products with the same activity_uuid_product_uuid will have the same transition risk score for the same benchmarks and therefore should only be counted once.
2. Rank the products based on their transition risk scores.
3. Define thresholds for classifying products into low, medium, and high risk categories for each of the transition_risk_score_benchmarks
- Determine the 1/3 percentile transition risk score as the threshold for low risk and share with @AnneSchoenauer at least the tilt_sector_unit and IPR 2030 benchmark
- Determine the 2/3 percentile transition risk score as the threshold for high risk and share with @AnneSchoenauer at least the tilt_sector_unit and IPR 2030 benchmark
4. Classify products with transition risk scores below the 1/3 percentile threshold as low risk, those above the 2/3 percentile threshold as high risk, and those in between as medium risk.
5. Test the implementation with sample datasets to ensure accuracy and reliability.
6. Optimize the code for efficiency and scalability, considering large datasets and potential future enhancements.

Here is a little piece of code (I cannot render it as a reprex for any reason) but the code should work: 

`# Sample dataset containing products and their transition risk scores (assumed to be between 0 and 1)
data <- data.frame(
  Product = c('A', 'B', 'C', 'A', 'B', 'C', 'A', 'B', 'C'),
  Transition_Risk_Score = c(0.2, 0.5, 0.8, 0.2, 0.5, 0.8, 0.2, 0.5, 0.8)
)

# Define thresholds for classifying products
percentiles <- quantile(data$Transition_Risk_Score, probs = c(1/3, 2/3))
low_threshold <- percentiles[1]
high_threshold <- percentiles[2]

# Classify products into low, medium, and high risk categories
risk_classification <- cut(data$Transition_Risk_Score,
                           breaks = c(0, low_threshold, high_threshold, 1),
                           labels = c("Low", "Medium", "High"),
                           include.lowest = TRUE)

# Add the risk category column to the data frame
data$Risk_Category <- risk_classification

# Print the updated data frame with the risk category column
print(data)
`

### PR DESCRIPTION
**Pull request by kalashsinghal**
closes 2DegreesInvesting/tiltIndicatorAfter#259 

Dear @Tilmon @AnneSchoenauer @maurolepore 

This PR adds the risk classification to transition risk scores. I have created a new function `profile_transition_risk` which creates the product and company level output of new `transition risk profile` indicator. It uses the `score_transition_risk_and_polish` from tiltIndicatorAfter and `add_thresholds_transition_risk` from tiltTransitionRisk to give us the complete results of transition risk scores with their risk classifications. 

Here is the reprex to check the final output at product and company level:

``` r
library(readr, warn.conflicts = FALSE)
library(dplyr, warn.conflicts = FALSE)
library(tiltToyData, warn.conflicts = FALSE)
library(tiltIndicatorAfter, warn.conflicts = FALSE)
devtools::load_all(".")
#> ℹ Loading tiltTransitionRisk
options(width = 500)

set.seed(123)
restore <- options(list(
  readr.show_col_types = FALSE,
  tiltIndicatorAfter.output_co2_footprint = TRUE
))

toy_emissions_profile_products_ecoinvent <- read_csv(toy_emissions_profile_products_ecoinvent())
toy_emissions_profile_any_companies <- read_csv(toy_emissions_profile_any_companies())
toy_sector_profile_any_scenarios <- read_csv(toy_sector_profile_any_scenarios())
toy_sector_profile_companies <- read_csv(toy_sector_profile_companies())
toy_europages_companies <- read_csv(toy_europages_companies())
toy_ecoinvent_activities <- read_csv(toy_ecoinvent_activities())
toy_ecoinvent_europages <- read_csv(toy_ecoinvent_europages())
toy_ecoinvent_inputs <- read_csv(toy_ecoinvent_inputs())
toy_isic_name <- read_csv(toy_isic_name())

emissions_profile <- profile_emissions(
  companies = toy_emissions_profile_any_companies,
  co2 = toy_emissions_profile_products_ecoinvent,
  europages_companies = toy_europages_companies,
  ecoinvent_activities = toy_ecoinvent_activities,
  ecoinvent_europages = toy_ecoinvent_europages,
  isic = toy_isic_name
)

sector_profile <- profile_sector(
  companies = toy_sector_profile_companies,
  scenarios = toy_sector_profile_any_scenarios,
  europages_companies = toy_europages_companies,
  ecoinvent_activities = toy_ecoinvent_activities,
  ecoinvent_europages = toy_ecoinvent_europages,
  isic = toy_isic_name
)

emissions_profile_products <- read_csv(toy_emissions_profile_products_ecoinvent())
all_uuids_scenario_sectors <- read_csv(toy_all_uuids_scenario_sectors())
scenarios <- read_csv(toy_sector_profile_any_scenarios())

output <- profile_transition_risk(emissions_profile,
  sector_profile,
  pivot_wider = FALSE,
  emissions_profile_products,
  all_uuids_scenario_sectors,
  scenarios
)

# product level output
output |> unnest_product() |> print(n = 30)
#> # A tibble: 1,824 × 23
#>    companies_id                       activity_uuid_product_uuid           transition_risk_score transition_risk_low_threshold transition_risk_high_threshold transition_risk_category benchmark_tr_score             profile_ranking reduction_targets country main_activity ep_product               matched_activity_name                                         matched_reference_product             co2e_lower co2e_upper emission_profile benchmark tilt_sector tilt_subsector sector_profile scenario  year
#>    <chr>                              <chr>                                                <dbl>                         <dbl>                          <dbl> <chr>                    <chr>                                    <dbl>             <dbl> <chr>   <chr>         <chr>                    <chr>                                                         <chr>                                      <dbl>      <dbl> <chr>            <chr>     <chr>       <chr>          <chr>          <chr>    <dbl>
#>  1 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.59                          0.366                          0.492 high                     1.5C RPS_2030_all                            1              0.18 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       45.5       767. high             all       constructi… construction … medium         1.5C RPS  2030
#>  2 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.99                          0.756                          0.872 high                     1.5C RPS_2050_all                            1              0.98 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       45.5       767. high             all       constructi… construction … high           1.5C RPS  2050
#>  3 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.7                           0.391                          0.532 high                     NZ 2050_2030_all                             1              0.4  austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       45.5       767. high             all       constructi… construction … high           NZ 2050   2030
#>  4 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.985                         0.751                          0.864 high                     NZ 2050_2050_all                             1              0.97 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       45.5       767. high             all       constructi… construction … high           NZ 2050   2050
#>  5 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.59                          0.575                          0.597 medium                   1.5C RPS_2030_isic_4digit                    1              0.18 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      269.        355. high             isic_4di… constructi… construction … medium         1.5C RPS  2030
#>  6 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.99                          0.978                          0.983 high                     1.5C RPS_2050_isic_4digit                    1              0.98 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      269.        355. high             isic_4di… constructi… construction … high           1.5C RPS  2050
#>  7 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.7                           0.613                          0.643 high                     NZ 2050_2030_isic_4digit                     1              0.4  austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      269.        355. high             isic_4di… constructi… construction … high           NZ 2050   2030
#>  8 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.985                         0.977                          0.982 high                     NZ 2050_2050_isic_4digit                     1              0.97 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      269.        355. high             isic_4di… constructi… construction … high           NZ 2050   2050
#>  9 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.59                          0.492                          0.597 medium                   1.5C RPS_2030_tilt_sector                    1              0.18 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       87.7       787. high             tilt_sec… constructi… construction … medium         1.5C RPS  2030
#> 10 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.99                          0.895                          0.983 high                     1.5C RPS_2050_tilt_sector                    1              0.98 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       87.7       787. high             tilt_sec… constructi… construction … high           1.5C RPS  2050
#> 11 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.7                           0.53                           0.643 high                     NZ 2050_2030_tilt_sector                     1              0.4  austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       87.7       787. high             tilt_sec… constructi… construction … high           NZ 2050   2030
#> 12 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.985                         0.89                           0.975 high                     NZ 2050_2050_tilt_sector                     1              0.97 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       87.7       787. high             tilt_sec… constructi… construction … high           NZ 2050   2050
#> 13 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.59                          0.492                          0.597 medium                   1.5C RPS_2030_unit                           1              0.18 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       94.4       536. high             unit      constructi… construction … medium         1.5C RPS  2030
#> 14 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.99                          0.895                          0.983 high                     1.5C RPS_2050_unit                           1              0.98 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       94.4       536. high             unit      constructi… construction … high           1.5C RPS  2050
#> 15 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.7                           0.53                           0.643 high                     NZ 2050_2030_unit                            1              0.4  austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       94.4       536. high             unit      constructi… construction … high           NZ 2050   2030
#> 16 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.985                         0.89                           0.975 high                     NZ 2050_2050_unit                            1              0.97 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       94.4       536. high             unit      constructi… construction … high           NZ 2050   2050
#> 17 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.59                          0.575                          0.597 medium                   1.5C RPS_2030_unit_isic_4digit               1              0.18 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      114.        417. high             unit_isi… constructi… construction … medium         1.5C RPS  2030
#> 18 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.99                          0.978                          0.983 high                     1.5C RPS_2050_unit_isic_4digit               1              0.98 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      114.        417. high             unit_isi… constructi… construction … high           1.5C RPS  2050
#> 19 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.7                           0.613                          0.643 high                     NZ 2050_2030_unit_isic_4digit                1              0.4  austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      114.        417. high             unit_isi… constructi… construction … high           NZ 2050   2030
#> 20 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.985                         0.977                          0.982 high                     NZ 2050_2050_unit_isic_4digit                1              0.97 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      114.        417. high             unit_isi… constructi… construction … high           NZ 2050   2050
#> 21 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.59                          0.492                          0.597 medium                   1.5C RPS_2030_unit_tilt_sector               1              0.18 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…     -258.        661. high             unit_til… constructi… construction … medium         1.5C RPS  2030
#> 22 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.99                          0.895                          0.983 high                     1.5C RPS_2050_unit_tilt_sector               1              0.98 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…     -258.        661. high             unit_til… constructi… construction … high           1.5C RPS  2050
#> 23 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.7                           0.53                           0.643 high                     NZ 2050_2030_unit_tilt_sector                1              0.4  austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…     -258.        661. high             unit_til… constructi… construction … high           NZ 2050   2030
#> 24 asteria_megalotomusquinquespinosus 76269c17-78d6-420b-991a-aa38c51b45b7                 0.985                         0.89                           0.975 high                     NZ 2050_2050_unit_tilt_sector                1              0.97 austria wholesaler    tent                     market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…     -258.        661. high             unit_til… constructi… construction … high           NZ 2050   2050
#> 25 skarn_gallinule                    76269c17-78d6-420b-991a-aa38c51b45b7                 0.59                          0.366                          0.492 high                     1.5C RPS_2030_all                            1              0.18 austria wholesaler    sheds, construction site market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       45.5       767. high             all       constructi… construction … medium         1.5C RPS  2030
#> 26 skarn_gallinule                    76269c17-78d6-420b-991a-aa38c51b45b7                 0.99                          0.756                          0.872 high                     1.5C RPS_2050_all                            1              0.98 austria wholesaler    sheds, construction site market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       45.5       767. high             all       constructi… construction … high           1.5C RPS  2050
#> 27 skarn_gallinule                    76269c17-78d6-420b-991a-aa38c51b45b7                 0.7                           0.391                          0.532 high                     NZ 2050_2030_all                             1              0.4  austria wholesaler    sheds, construction site market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       45.5       767. high             all       constructi… construction … high           NZ 2050   2030
#> 28 skarn_gallinule                    76269c17-78d6-420b-991a-aa38c51b45b7                 0.985                         0.751                          0.864 high                     NZ 2050_2050_all                             1              0.97 austria wholesaler    sheds, construction site market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…       45.5       767. high             all       constructi… construction … high           NZ 2050   2050
#> 29 skarn_gallinule                    76269c17-78d6-420b-991a-aa38c51b45b7                 0.59                          0.575                          0.597 medium                   1.5C RPS_2030_isic_4digit                    1              0.18 austria wholesaler    sheds, construction site market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      269.        355. high             isic_4di… constructi… construction … medium         1.5C RPS  2030
#> 30 skarn_gallinule                    76269c17-78d6-420b-991a-aa38c51b45b7                 0.99                          0.978                          0.983 high                     1.5C RPS_2050_isic_4digit                    1              0.98 austria wholesaler    sheds, construction site market for shed, large, wood, non-insulated, fire-unprotected shed, large, wood, non-insulated, fi…      269.        355. high             isic_4di… constructi… construction … high           1.5C RPS  2050
#> # ℹ 1,794 more rows

# company level output
output |> unnest_company() |> print(n = 30)
#> # A tibble: 6,912 × 13
#>    companies_id                       country main_activity benchmark_tr_score_avg    benchmark   emission_profile emission_profile_share profile_ranking_avg co2_avg scenario year  reduction_targets_avg transition_risk_score_avg
#>    <chr>                              <chr>   <chr>         <chr>                     <chr>       <chr>                             <dbl>               <dbl>   <dbl> <chr>    <chr>                 <dbl>                     <dbl>
#>  1 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2030_all         all         high                                  1                   1    303. 1.5C RPS 2030                   0.18                     0.59 
#>  2 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2050_all         all         high                                  1                   1    303. 1.5C RPS 2050                   0.98                     0.99 
#>  3 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2030_all          all         high                                  1                   1    303. NZ 2050  2030                   0.4                      0.7  
#>  4 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2050_all          all         high                                  1                   1    303. NZ 2050  2050                   0.97                     0.985
#>  5 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2030_all         all         medium                                0                   1    303. 1.5C RPS 2030                   0.18                     0.59 
#>  6 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2050_all         all         medium                                0                   1    303. 1.5C RPS 2050                   0.98                     0.99 
#>  7 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2030_all          all         medium                                0                   1    303. NZ 2050  2030                   0.4                      0.7  
#>  8 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2050_all          all         medium                                0                   1    303. NZ 2050  2050                   0.97                     0.985
#>  9 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2030_all         all         low                                   0                   1    303. 1.5C RPS 2030                   0.18                     0.59 
#> 10 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2050_all         all         low                                   0                   1    303. 1.5C RPS 2050                   0.98                     0.99 
#> 11 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2030_all          all         low                                   0                   1    303. NZ 2050  2030                   0.4                      0.7  
#> 12 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2050_all          all         low                                   0                   1    303. NZ 2050  2050                   0.97                     0.985
#> 13 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2030_all         all         <NA>                                  0                   1    303. 1.5C RPS 2030                   0.18                     0.59 
#> 14 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2050_all         all         <NA>                                  0                   1    303. 1.5C RPS 2050                   0.98                     0.99 
#> 15 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2030_all          all         <NA>                                  0                   1    303. NZ 2050  2030                   0.4                      0.7  
#> 16 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2050_all          all         <NA>                                  0                   1    303. NZ 2050  2050                   0.97                     0.985
#> 17 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2030_isic_4digit isic_4digit high                                  1                   1    303. 1.5C RPS 2030                   0.18                     0.59 
#> 18 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2050_isic_4digit isic_4digit high                                  1                   1    303. 1.5C RPS 2050                   0.98                     0.99 
#> 19 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2030_isic_4digit  isic_4digit high                                  1                   1    303. NZ 2050  2030                   0.4                      0.7  
#> 20 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2050_isic_4digit  isic_4digit high                                  1                   1    303. NZ 2050  2050                   0.97                     0.985
#> 21 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2030_isic_4digit isic_4digit medium                                0                   1    303. 1.5C RPS 2030                   0.18                     0.59 
#> 22 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2050_isic_4digit isic_4digit medium                                0                   1    303. 1.5C RPS 2050                   0.98                     0.99 
#> 23 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2030_isic_4digit  isic_4digit medium                                0                   1    303. NZ 2050  2030                   0.4                      0.7  
#> 24 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2050_isic_4digit  isic_4digit medium                                0                   1    303. NZ 2050  2050                   0.97                     0.985
#> 25 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2030_isic_4digit isic_4digit low                                   0                   1    303. 1.5C RPS 2030                   0.18                     0.59 
#> 26 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2050_isic_4digit isic_4digit low                                   0                   1    303. 1.5C RPS 2050                   0.98                     0.99 
#> 27 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2030_isic_4digit  isic_4digit low                                   0                   1    303. NZ 2050  2030                   0.4                      0.7  
#> 28 asteria_megalotomusquinquespinosus austria wholesaler    NZ 2050_2050_isic_4digit  isic_4digit low                                   0                   1    303. NZ 2050  2050                   0.97                     0.985
#> 29 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2030_isic_4digit isic_4digit <NA>                                  0                   1    303. 1.5C RPS 2030                   0.18                     0.59 
#> 30 asteria_megalotomusquinquespinosus austria wholesaler    1.5C RPS_2050_isic_4digit isic_4digit <NA>                                  0                   1    303. 1.5C RPS 2050                   0.98                     0.99 
#> # ℹ 6,882 more rows
```

<sup>Created on 2024-06-06 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

----

TODO

- [x] Draft the PR title.
- [x] [Link related issue/PR]([url](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword)). 
- [x] Draft the PR description.
- [x] Mark the PR as draft.
- [x] [Include a unit test](https://code-review.tidyverse.org/reviewer/aspects.html#sec-tests).
- [x] Review your own PR in "Files changed".
- [x] Ensure the PR branch is updated.
- [x] Ensure all checks pass.
- [x] Change the PR status from draft to ready.
- [ ] Polish the PR description to reflect it's goal (why not how).
- [ ] Polish the PR title as you'd like others to read it from the git log.
- [x] Assign a reviewer.

Also if the PR includes user-facing changes:

- [ ] Increment the version number: `fledge::update_version()`
- [ ] Update the changelog: `fledge::update_news()`
- [ ] Merge then tag: `fledge::tag_version()`

### CODE REVIEW

**Comment by Tilmon** [comment]
@kalashsinghal looks good to me! Only one suggestion, curious to hear your and @AnneSchoenauer 's thoughts: I think it would make the output more user friendly if for each company it was grouped by the column `benchmark_tr_score_avg` so that one sees per `benchmark_tr_score_avg` the four categories (high, medium, low, NA), instead of right now seeing each category four times in a row because it's grouped differently. What do you think?

**Comment by Tilmon** [comment]
@kalashsinghal 
Ah, one more thing: When reproducing the output, I saw that `emission_profile()` adds 37% and 97% noise to `co2e_lower `and `co2e_upper`... I thought this has been changed in the past to less noise? It seems odd to me that if a `co2_footprint `is 300, the co2e_lower is almost 0...

cc' @AnneSchoenauer

**Comment by AnneSchoenauer** [comment]
Hi both - yes! it all looks good to me! Well done @kalashsinghal!

I agree with this!

> @kalashsinghal looks good to me! Only one suggestion, curious to hear your and @AnneSchoenauer 's thoughts: I think it would make the output more user friendly if for each company it was grouped by the column benchmark_tr_score_avg so that one sees per benchmark_tr_score_avg the four categories (high, medium, low, NA), instead of right now seeing each category four times in a row because it's grouped differently. What do you think?

Aaaand I guess the co2_lower and _upper column is something that is not wrong with the transition_risk_indicator right? So maybe good to write a separate ticket? @Tilmon as a bug to investigate next week before the Tech sprint?

**Review by maurolepore — COMMENTED** [review]
Thanks @kalashsinghal 

Here are some general comments:

## ARCHITECTURE

This is the architecture I see. The tiltTransitionRisk package depends on tiltIndicator and tiltIndicatorAfter (as reflected in DESCRIPTION/Imports).

```
tiltIndicator
--------------> tiltIndicatorAfter
------------------------------------> tiltTransitionRisk
```

This is the architecture I believe is best. For this you may need to keep the highes-level function in tiltTransitionRisk and import them from tiltIndicatorAfter.

```
tiltIndicator
tiltTransitionRisk
--------------------> tiltIndicatorAfter
```

## NAME

These are the names we currently have. It would be best to stay consistent:

* The `<indicator>_profile()` functions are higher-level (closer to the business logic)
* The `profile_<indicator>()` functions are lower-level (closer to the user)

Note the names will eventually change ([issue](https://github.com/2DegreesInvesting/TiltDevProjectMGMT/issues/166)) to `<indicator>_indicator()` and `indicaor_<indicator>()`. But for now it's probabbly best to stay consistent with what we already have.

## ARGUMENTS

> * Optional arguments (i.e. arguments with a default) are the least important, and should come last.
> --https://design.tidyverse.org/important-args-first.html

```r
good <- function(x, y = TRUE) {...}
bad1 <- function(y = TRUE, x) {...}
bad2 <- function(x, y = TRUE, z) {...}
```

Can we make the signature of the new function closer to the other related functions? This helps users because learning one function makes it easier to learn any other function.

Her is an example of one related function:

```r
profile_emissions(
  companies,
  co2,
  europages_companies,
  ecoinvent_activities,
  ecoinvent_europages,
  isic,
  isic_tilt = lifecycle::deprecated(),
  low_threshold = 1/3,
  high_threshold = 2/3
)
```

Note the pattern:

```r
profile_emissions(
  <datasets>,
  <mappers>,
  <thresholds>
)
```

**Comment by kalashsinghal** [comment]
> This is the architecture I believe is best. For this you may need to keep the highes-level function in tiltTransitionRisk and import them from tiltIndicatorAfter.

I will shift this PR to tiltIndicatorAfter to implement the architectural change suggested by Mauro. I will address all the comments in that PR.

**Pull request closed without merging**
